version: '3.8'

services:
  # 1. Tu aplicación Web principal
  angelo:
    image: ghcr.io/mrzukox/angel-troy:latest
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Rutas HTTP -> HTTPS
      - "traefik.http.routers.angelo.entrypoints=http"
      - "traefik.http.routers.angelo.rule=Host('angelo.byronrm.com')"
      - "traefik.http.routers.angelo.middlewares=redirect-to-https"
      # Rutas HTTPS Seguras
      - "traefik.http.routers.angelo-secure.entrypoints=https"
      - "traefik.http.routers.angelo-secure.rule=Host('angelo.byronrm.com')"
      - "traefik.http.routers.angelo-secure.tls=true"
      - "traefik.http.routers.angelo-secure.tls.certresolver=http"
      - "traefik.http.routers.angelo-secure.service=angelo-svc"
      - "traefik.http.services.angelo-svc.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-public"
    deploy:
      replicas: 1

  # 2. El administrador de Base de Datos (Si usas pgAdmin para pgangeltroy)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@byronrm.com
      PGADMIN_DEFAULT_PASSWORD: tu_password_seguro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgangeltroy-secure.entrypoints=https"
      - "traefik.http.routers.pgangeltroy-secure.rule=Host('pgangeltroy.byronrm.com')"
      - "traefik.http.routers.pgangeltroy-secure.tls=true"
      - "traefik.http.routers.pgangeltroy-secure.tls.certresolver=http"
      - "traefik.http.routers.pgangeltroy-secure.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=80" # pgAdmin usa el puerto 80 interno
      - "traefik.docker.network=traefik-public"
    deploy:
      replicas: 1

networks:
  traefik-public:
    external: true