version: '3.8'

services:
  angelo:
    image: ghcr.io/mrzukox/angel-troy:latest
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # Configuración para HTTP
      - "traefik.http.routers.angelo.entrypoints=http"
      - "traefik.http.routers.angelo.rule=Host(\`angelo.byronrm.com\`)"
      - "traefik.http.routers.angelo.middlewares=redirect-to-https"
      - "traefik.http.routers.angelo.service=angelo-svc"
      
      # Configuración para HTTPS
      - "traefik.http.routers.angelo-secure.entrypoints=https"
      - "traefik.http.routers.angelo-secure.rule=Host(\`angelo.byronrm.com\`)"
      - "traefik.http.routers.angelo-secure.tls=true"
      - "traefik.http.routers.angelo-secure.tls.certresolver=http"
      - "traefik.http.routers.angelo-secure.service=angelo-svc"
      
      # Puerto interno de tu Flask
      - "traefik.http.services.angelo-svc.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-public"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true