services:
  angelo:
    image: ghcr.io/mrzukox/angel-troy:latest

    networks:
      - traefik-public

    labels:
      # =========================
      # Configuración general
      # =========================
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      # Puerto interno de la aplicación Flask
      - "traefik.http.services.angelo.loadbalancer.server.port=5000"

      # Middleware para redireccionar HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # =====================================================
      # angelo.byronrm.com
      # =====================================================

      # HTTP
      - "traefik.http.routers.angelo.rule=Host(`angelo.byronrm.com`)"
      - "traefik.http.routers.angelo.entrypoints=web"
      - "traefik.http.routers.angelo.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.angelo-secure.rule=Host(`angelo.byronrm.com`)"
      - "traefik.http.routers.angelo-secure.entrypoints=websecure"
      - "traefik.http.routers.angelo-secure.tls=true"
      - "traefik.http.routers.angelo-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.angelo-secure.service=angelo"

      # =====================================================
      # pgangeltroy.byronrm.com
      # =====================================================

      # HTTP
      - "traefik.http.routers.pgangeltroy.rule=Host(`pgangeltroy.byronrm.com`)"
      - "traefik.http.routers.pgangeltroy.entrypoints=web"
      - "traefik.http.routers.pgangeltroy.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.pgangeltroy-secure.rule=Host(`pgangeltroy.byronrm.com`)"
      - "traefik.http.routers.pgangeltroy-secure.entrypoints=websecure"
      - "traefik.http.routers.pgangeltroy-secure.tls=true"
      - "traefik.http.routers.pgangeltroy-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pgangeltroy-secure.service=angelo"

      # =====================================================
      # portainerat.byronrm.com
      # =====================================================

      # HTTP
      - "traefik.http.routers.portainerat.rule=Host(`portainerat.byronrm.com`)"
      - "traefik.http.routers.portainerat.entrypoints=web"
      - "traefik.http.routers.portainerat.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.portainerat-secure.rule=Host(`portainerat.byronrm.com`)"
      - "traefik.http.routers.portainerat-secure.entrypoints=websecure"
      - "traefik.http.routers.portainerat-secure.tls=true"
      - "traefik.http.routers.portainerat-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainerat-secure.service=angelo"

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure

      update_config:
        parallelism: 1
        delay: 10s

networks:
  traefik-public:
    external: true